# Generated by Django 5.1.4 on 2025-01-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('cuisine_style', models.TextField()),
                ('ranking', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, max_length=20)),
                ('number_of_reviews', models.IntegerField(blank=True, null=True)),
                ('reviews', models.TextField(blank=True)),
                ('url_ta', models.URLField(blank=True)),
                ('id_ta', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
