# Generated by Django 5.1.4 on 2025-01-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='number_of_reviews',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
