# Generated by Django 5.1.4 on 2025-01-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataviewer', '0002_alter_restaurant_number_of_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='ranking',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='number_of_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
