# Generated by Django 5.1.4 on 2025-01-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('cuisine', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('visit_count', models.IntegerField()),
                ('allergy', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
